### ISSUE TITLE
admin 建立文章的 url issue

### ISSUE THREAD

**Issue by clonn** [nodejs-tw/nodeclub#7]
admin 建立文章時候，無法建立符合的 url ，方便使用者記憶連結。

如果可以的話，希望能把此功能加上去。

**Comment by poying** [comment]
是指讓管理者手動設定嗎？

**Comment by clonn** [comment]
是的
一個 input 讓 admin 可以手動輸入 url

**Comment by poying** [comment]
文章加入自訂網址了
https://github.com/nodejs-tw/nodeclub/commit/6d52e5cb7376e6fa00df31f041c186cdf07a01f7
